name: CD
on:
  workflow_call:
    inputs:
      target:
        description: Publishing target excluding '@' sign e.g. 'latest', 'next'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up
        uses: ./.github/actions/setup
        with:
          auth: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Checkout build artifact
        uses: actions/download-artifact@v3
        with:
          name: package
          path: dist

      - run: npm publish --tag ${{ inputs.target }}
