name: CD
on:
  workflow_call:
    inputs:
      target:
        description: Publishing target excluding '@' sign e.g. 'latest', 'next'
        required: false
        default: latest
        type: string
      version-suffix:
        description: |
          Version suffix to programatically add to package version e.g. 'rc3'.
          Only used if target is not `latest`.
        required: false
        default: ${{ inputs.target }}${{ github.run_id }}
        type: string
      environment:
        description: The GitHub environment to utilize for deployement
        required: true
        type: string
    secrets:
      NPM_AUTH_TOKEN:
        description: npm authentication token used for publishing
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up
        uses: ./.github/actions/setup

      - name: Checkout build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Infer version from git tag
        if: inputs.target == 'latest'
        run: npm version from-git

      - name: Add version suffix
        if: inputs.target != 'latest'
        run: |
          VER=$(node -e 'console.log(require("./package.json").version)')
          npm version "${VER}-${{inputs.version-suffix}}"

      - run: npm publish --tag ${{ inputs.target }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
