on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  docs:
    uses: ./.github/workflows/documentation.yml

  cd:
    needs: ci
    uses: ./.github/workflows/cd.yml
    with:
      target: next
    secrets:
      auth: ${{ secrets.NODE_AUTH_TOKEN }}
