name: Release published
on:
  release:
    types:
      - published

jobs:
  ci:
    name: Run CI pipeline
    uses: ./.github/workflows/ci.yml

  cd:
    name: Publish package
    needs: ci
    uses: ./.github/workflows/cd.yml
    with:
      target: current
      environment: release
